[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = ['pip install -r requirements_clean.txt']

[phases.build]
cmds = ['echo "Build completed - no build step needed for Python bot"']

[start]
cmd = 'python telegram_bot_main.py'